[Interface]
Address = 10.8.1.1/24
ListenPort = 40100
PrivateKey = <REDACTED>
Jc = 8
Jmin = 24
Jmax = 106
S1 = 68
S2 = 149
H1 = 153007901
H2 = 1536947925
H3 = 912599611
H4 = 1876804433
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.2/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.3/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.4/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.5/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.6/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.7/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.8/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.9/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.10/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.11/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.12/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.13/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.14/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.15/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.16/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.17/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.18/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.19/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.20/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.21/32

[Peer]
PublicKey = <REDACTED>
AllowedIPs = 10.8.1.22/32
